### ISSUE TITLE
CSV has no line-ending

### ISSUE THREAD

**Issue by reinvented** [lesander/netflix-viewing-activity#1]
Using Chrome Version 60.0.3112.78 (Official Build) (64-bit) on a MacBook Air running macOS High Sierra, when I use the extension to export my viewing activity as a CSV, the resulting file has no line-endings: it's one long, lone line to text. With no obvious delimiter at the end of each record, it seems impossible to import this into a spreadsheet.

I was able to workaround by exporting to JSON and then converting from JSON to CSV.

**Comment by lesander** [comment]
Hi Peter, thank you for creating this issue. I'll fix this asap. 

I've reproduced your issue and proper line endings indeed seem to be missing. Excel has trouble opening the exported csv, however Apple's Numbers app seems to be fine with it.

**Comment by reinvented** [comment]
Thank you!

You've created a really great tool, and one that saved me a lot of work. Here's what resulted, in part:

https://ruk.ca/content/personal-netflix-analytics

https://ruk.ca/content/visualizing-our-netflix-streaming-activity-calendar

Cheers,
Peter
