### ISSUE TITLE
Upload exported data

### ISSUE THREAD

**Issue by filipef101** [lesander/netflix-viewing-activity#10]
Hey, do you guys know any way I can upload this data, ex to merge an old account with a new one?
Also is it possible to export "my list" items?

**Comment by lesander** [comment]
Hi Filipe! Thank you for creating this issue and my apologies for the late reply.

As far as I'm aware there's no way to "import" viewing history into a new account. Perhaps you'd need to find a way to fake Netflix's API calls related to viewing history when you normally watch an episode or movie. 

I haven't looked into the "my list" items. I figure that if there's an API call for it, it would be possible yes.

**Comment by filipef101** [comment]
Thanks for the reply. I'm no longer in need for this functionality but I think it may be useful for someone else. Feel free to close if you wish.
