### ISSUE TITLE
Only exporting one page of viewing history

### ISSUE THREAD

**Issue by glauser** [lesander/netflix-viewing-activity#3]
Thanks for an elegant tool!  I'm using Chrome 67.0.3396.87 on macOS 10.13.5, and the tool will only export the first page of viewing activity, regardless of how many 'pages' I've got open (ie: how many times I've pressed Show More).

I haven't been able to fix it on my own, I'm nowhere near good enough with JS.

Thanks!

**Comment by Excommunicated** [comment]
The issue appears to be that Neflix will only send 20 results at a time, regardless of the requested pgSize query parameter.
In [inject.js](https://github.com/lesander/netflix-viewing-activity/blob/master/src/js/inject.js), change line 120 from
`const pageSize = 100`
to
`const pageSize = 20`

**Comment by lesander** [comment]
Thanks @Excommunicated for diving in to this API change! I’ll close this issue as soon as version 1.0.2 is released on the Chrome Web Store.
