### ISSUE TITLE
Netflix API has changed, breaks extension

### ISSUE THREAD

**Issue by lesander** [lesander/netflix-viewing-activity#7]
I've identified two problems with the current NVA extension:

1. The constant `window.netflix.reactContext.models.serverDefs.data.API_BASE_URL` does not exist anymore. It seems to be replaced with `window.netflix.reactContext.models.serverDefs.data.API_ROOT = "https://www.netflix.com/api"` and the object `window.netflix.reactContext.models.services.data.api`:
    ```js
    {
        hostname: "www.netflix.com",
        name: "api",
        path: [ "api", "shakti"]
        protocol: "https"
        secure: false
    }
    ```
    In order to fix this we need to fix the way we build our api uri. This is the current situation:
    ```js
    const url = `https://www.netflix.com/api${apiBaseUrl}/` +
                `${buildIdentifier}/${type}` +
                `?pg=${pageNum}&pgSize=${pageSize}&_=${timestamp}` +
                `&authURL=${authUrl}`
    ```
    **After some testing it seems that changing `apiBaseUrl = "/shakti"` fixes the API calls.**

2. CSV export is broken, only the first twenty entries are visible in exported sheets. JSON seems to be fine.

**Comment by lordlycastle** [comment]
@lesander update?

**Comment by plotka** [comment]
@lesander Can I submit a pull request to fix this?

**Comment by lordlycastle** [comment]
@plotka Yes! Or just fork it!

**Comment by lesander** [comment]
Hi @plotka, of course! Your pull request is more than welcome!

**Comment by plotka** [comment]
@lesander Done #8

**Comment by lesander** [comment]
Thank you @plotka for your fix, I'll deploy the changes to the chrome store shortly.

**Comment by lesander** [comment]
Version 1.1.1 has been submitted to the chrome store for review.

**Comment by lesander** [comment]
The latest version is now published on the chrome store.
